name: Build and deploys
run-name: ${{ github.actor }} is learning GitHub Actions
push:
    branches:
      - "main"
jobs:
  check-out-repository:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -la
